from __future__ import annotations

import json
import os
from typing import Any, Dict

from music_document import compact_for_llm

SYSTEM_PROMPT = """You are the music reasoning layer for YouTube Music Notes.
You receive a structured MusicDocument generated by transcription software.
Treat transcription fields as observations, not perfect ground truth. Explicitly mention uncertainty
when it matters. Help the learner understand harmony, melody, rhythm, technique, fingering,
arrangement and practice strategy. Never pretend missing key/tempo/chord fields were detected.
When useful, suggest concrete exercises and simpler arrangements appropriate to the requested instrument.
"""


def _openai_reason(document: Dict[str, Any], question: str) -> str:
    from openai import OpenAI

    client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
    model = os.environ.get("OPENAI_MODEL", "gpt-5-mini")
    response = client.responses.create(
        model=model,
        instructions=SYSTEM_PROMPT,
        input=(
            f"MusicDocument:\n{json.dumps(compact_for_llm(document), ensure_ascii=False)}\n\n"
            f"Learner request:\n{question}"
        ),
    )
    return response.output_text


def _gemini_reason(document: Dict[str, Any], question: str) -> str:
    from google import genai

    client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))
    model = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")
    response = client.models.generate_content(
        model=model,
        contents=(
            f"{SYSTEM_PROMPT}\n\n"
            f"MusicDocument:\n{json.dumps(compact_for_llm(document), ensure_ascii=False)}\n\n"
            f"Learner request:\n{question}"
        ),
    )
    return response.text or ""


def reason_about_music(document: Dict[str, Any], question: str, provider: str | None = None) -> Dict[str, str]:
    provider = (provider or os.environ.get("DEFAULT_LLM_PROVIDER", "openai")).strip().lower()

    if provider == "openai":
        if not os.environ.get("OPENAI_API_KEY"):
            raise RuntimeError("OPENAI_API_KEY is not configured")
        answer = _openai_reason(document, question)
    elif provider == "gemini":
        if not os.environ.get("GEMINI_API_KEY"):
            raise RuntimeError("GEMINI_API_KEY is not configured")
        answer = _gemini_reason(document, question)
    else:
        raise ValueError("provider must be 'openai' or 'gemini'")

    return {"provider": provider, "answer": answer}
